<?php

/**
 * Base class that represents a row from the 'domicilio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct  2 02:27:16 2012
 *
 * @package    lib.model.om
 */
abstract class BaseDomicilio extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        DomicilioPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the persona_id field.
	 * @var        int
	 */
	protected $persona_id;

	/**
	 * The value for the provincia_id field.
	 * @var        int
	 */
	protected $provincia_id;

	/**
	 * The value for the localidad_id field.
	 * @var        int
	 */
	protected $localidad_id;

	/**
	 * The value for the telefono field.
	 * @var        string
	 */
	protected $telefono;

	/**
	 * The value for the calle field.
	 * @var        string
	 */
	protected $calle;

	/**
	 * The value for the altura field.
	 * @var        string
	 */
	protected $altura;

	/**
	 * The value for the piso field.
	 * @var        string
	 */
	protected $piso;

	/**
	 * The value for the dpto field.
	 * @var        string
	 */
	protected $dpto;

	/**
	 * The value for the codigo_postal field.
	 * @var        string
	 */
	protected $codigo_postal;

	/**
	 * The value for the escalera field.
	 * @var        string
	 */
	protected $escalera;

	/**
	 * The value for the torre field.
	 * @var        string
	 */
	protected $torre;

	/**
	 * The value for the nudo field.
	 * @var        string
	 */
	protected $nudo;

	/**
	 * The value for the ala field.
	 * @var        string
	 */
	protected $ala;

	/**
	 * The value for the parcela field.
	 * @var        string
	 */
	protected $parcela;

	/**
	 * The value for the entre_calles field.
	 * @var        string
	 */
	protected $entre_calles;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the created_by_id field.
	 * @var        int
	 */
	protected $created_by_id;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the updated_by_id field.
	 * @var        int
	 */
	protected $updated_by_id;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * The value for the deleted_by_id field.
	 * @var        int
	 */
	protected $deleted_by_id;

	/**
	 * @var        Persona
	 */
	protected $aPersona;

	/**
	 * @var        Provincia
	 */
	protected $aProvincia;

	/**
	 * @var        Localidad
	 */
	protected $aLocalidad;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByCreatedById;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByUpdatedById;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByDeletedById;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'DomicilioPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [persona_id] column value.
	 * 
	 * @return     int
	 */
	public function getPersonaId()
	{
		return $this->persona_id;
	}

	/**
	 * Get the [provincia_id] column value.
	 * 
	 * @return     int
	 */
	public function getProvinciaId()
	{
		return $this->provincia_id;
	}

	/**
	 * Get the [localidad_id] column value.
	 * 
	 * @return     int
	 */
	public function getLocalidadId()
	{
		return $this->localidad_id;
	}

	/**
	 * Get the [telefono] column value.
	 * 
	 * @return     string
	 */
	public function getTelefono()
	{
		return $this->telefono;
	}

	/**
	 * Get the [calle] column value.
	 * 
	 * @return     string
	 */
	public function getCalle()
	{
		return $this->calle;
	}

	/**
	 * Get the [altura] column value.
	 * 
	 * @return     string
	 */
	public function getAltura()
	{
		return $this->altura;
	}

	/**
	 * Get the [piso] column value.
	 * 
	 * @return     string
	 */
	public function getPiso()
	{
		return $this->piso;
	}

	/**
	 * Get the [dpto] column value.
	 * 
	 * @return     string
	 */
	public function getDpto()
	{
		return $this->dpto;
	}

	/**
	 * Get the [codigo_postal] column value.
	 * 
	 * @return     string
	 */
	public function getCodigoPostal()
	{
		return $this->codigo_postal;
	}

	/**
	 * Get the [escalera] column value.
	 * 
	 * @return     string
	 */
	public function getEscalera()
	{
		return $this->escalera;
	}

	/**
	 * Get the [torre] column value.
	 * 
	 * @return     string
	 */
	public function getTorre()
	{
		return $this->torre;
	}

	/**
	 * Get the [nudo] column value.
	 * 
	 * @return     string
	 */
	public function getNudo()
	{
		return $this->nudo;
	}

	/**
	 * Get the [ala] column value.
	 * 
	 * @return     string
	 */
	public function getAla()
	{
		return $this->ala;
	}

	/**
	 * Get the [parcela] column value.
	 * 
	 * @return     string
	 */
	public function getParcela()
	{
		return $this->parcela;
	}

	/**
	 * Get the [entre_calles] column value.
	 * 
	 * @return     string
	 */
	public function getEntreCalles()
	{
		return $this->entre_calles;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [created_by_id] column value.
	 * 
	 * @return     int
	 */
	public function getCreatedById()
	{
		return $this->created_by_id;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [updated_by_id] column value.
	 * 
	 * @return     int
	 */
	public function getUpdatedById()
	{
		return $this->updated_by_id;
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}


		if ($this->deleted_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->deleted_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [deleted_by_id] column value.
	 * 
	 * @return     int
	 */
	public function getDeletedById()
	{
		return $this->deleted_by_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = DomicilioPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [persona_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setPersonaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->persona_id !== $v) {
			$this->persona_id = $v;
			$this->modifiedColumns[] = DomicilioPeer::PERSONA_ID;
		}

		if ($this->aPersona !== null && $this->aPersona->getId() !== $v) {
			$this->aPersona = null;
		}

		return $this;
	} // setPersonaId()

	/**
	 * Set the value of [provincia_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setProvinciaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->provincia_id !== $v) {
			$this->provincia_id = $v;
			$this->modifiedColumns[] = DomicilioPeer::PROVINCIA_ID;
		}

		if ($this->aProvincia !== null && $this->aProvincia->getId() !== $v) {
			$this->aProvincia = null;
		}

		return $this;
	} // setProvinciaId()

	/**
	 * Set the value of [localidad_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setLocalidadId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->localidad_id !== $v) {
			$this->localidad_id = $v;
			$this->modifiedColumns[] = DomicilioPeer::LOCALIDAD_ID;
		}

		if ($this->aLocalidad !== null && $this->aLocalidad->getId() !== $v) {
			$this->aLocalidad = null;
		}

		return $this;
	} // setLocalidadId()

	/**
	 * Set the value of [telefono] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setTelefono($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono !== $v) {
			$this->telefono = $v;
			$this->modifiedColumns[] = DomicilioPeer::TELEFONO;
		}

		return $this;
	} // setTelefono()

	/**
	 * Set the value of [calle] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setCalle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->calle !== $v) {
			$this->calle = $v;
			$this->modifiedColumns[] = DomicilioPeer::CALLE;
		}

		return $this;
	} // setCalle()

	/**
	 * Set the value of [altura] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setAltura($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->altura !== $v) {
			$this->altura = $v;
			$this->modifiedColumns[] = DomicilioPeer::ALTURA;
		}

		return $this;
	} // setAltura()

	/**
	 * Set the value of [piso] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setPiso($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->piso !== $v) {
			$this->piso = $v;
			$this->modifiedColumns[] = DomicilioPeer::PISO;
		}

		return $this;
	} // setPiso()

	/**
	 * Set the value of [dpto] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setDpto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dpto !== $v) {
			$this->dpto = $v;
			$this->modifiedColumns[] = DomicilioPeer::DPTO;
		}

		return $this;
	} // setDpto()

	/**
	 * Set the value of [codigo_postal] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setCodigoPostal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->codigo_postal !== $v) {
			$this->codigo_postal = $v;
			$this->modifiedColumns[] = DomicilioPeer::CODIGO_POSTAL;
		}

		return $this;
	} // setCodigoPostal()

	/**
	 * Set the value of [escalera] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setEscalera($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->escalera !== $v) {
			$this->escalera = $v;
			$this->modifiedColumns[] = DomicilioPeer::ESCALERA;
		}

		return $this;
	} // setEscalera()

	/**
	 * Set the value of [torre] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setTorre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->torre !== $v) {
			$this->torre = $v;
			$this->modifiedColumns[] = DomicilioPeer::TORRE;
		}

		return $this;
	} // setTorre()

	/**
	 * Set the value of [nudo] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setNudo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nudo !== $v) {
			$this->nudo = $v;
			$this->modifiedColumns[] = DomicilioPeer::NUDO;
		}

		return $this;
	} // setNudo()

	/**
	 * Set the value of [ala] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setAla($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ala !== $v) {
			$this->ala = $v;
			$this->modifiedColumns[] = DomicilioPeer::ALA;
		}

		return $this;
	} // setAla()

	/**
	 * Set the value of [parcela] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setParcela($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->parcela !== $v) {
			$this->parcela = $v;
			$this->modifiedColumns[] = DomicilioPeer::PARCELA;
		}

		return $this;
	} // setParcela()

	/**
	 * Set the value of [entre_calles] column.
	 * 
	 * @param      string $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setEntreCalles($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->entre_calles !== $v) {
			$this->entre_calles = $v;
			$this->modifiedColumns[] = DomicilioPeer::ENTRE_CALLES;
		}

		return $this;
	} // setEntreCalles()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = DomicilioPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [created_by_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setCreatedById($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->created_by_id !== $v) {
			$this->created_by_id = $v;
			$this->modifiedColumns[] = DomicilioPeer::CREATED_BY_ID;
		}

		if ($this->asfGuardUserRelatedByCreatedById !== null && $this->asfGuardUserRelatedByCreatedById->getId() !== $v) {
			$this->asfGuardUserRelatedByCreatedById = null;
		}

		return $this;
	} // setCreatedById()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = DomicilioPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [updated_by_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setUpdatedById($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->updated_by_id !== $v) {
			$this->updated_by_id = $v;
			$this->modifiedColumns[] = DomicilioPeer::UPDATED_BY_ID;
		}

		if ($this->asfGuardUserRelatedByUpdatedById !== null && $this->asfGuardUserRelatedByUpdatedById->getId() !== $v) {
			$this->asfGuardUserRelatedByUpdatedById = null;
		}

		return $this;
	} // setUpdatedById()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deleted_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deleted_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = DomicilioPeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Set the value of [deleted_by_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Domicilio The current object (for fluent API support)
	 */
	public function setDeletedById($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->deleted_by_id !== $v) {
			$this->deleted_by_id = $v;
			$this->modifiedColumns[] = DomicilioPeer::DELETED_BY_ID;
		}

		if ($this->asfGuardUserRelatedByDeletedById !== null && $this->asfGuardUserRelatedByDeletedById->getId() !== $v) {
			$this->asfGuardUserRelatedByDeletedById = null;
		}

		return $this;
	} // setDeletedById()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->persona_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->provincia_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->localidad_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->telefono = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->calle = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->altura = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->piso = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->dpto = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->codigo_postal = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->escalera = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->torre = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->nudo = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->ala = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->parcela = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->entre_calles = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->created_at = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->created_by_id = ($row[$startcol + 17] !== null) ? (int) $row[$startcol + 17] : null;
			$this->updated_at = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->updated_by_id = ($row[$startcol + 19] !== null) ? (int) $row[$startcol + 19] : null;
			$this->deleted_at = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->deleted_by_id = ($row[$startcol + 21] !== null) ? (int) $row[$startcol + 21] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 22; // 22 = DomicilioPeer::NUM_COLUMNS - DomicilioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Domicilio object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPersona !== null && $this->persona_id !== $this->aPersona->getId()) {
			$this->aPersona = null;
		}
		if ($this->aProvincia !== null && $this->provincia_id !== $this->aProvincia->getId()) {
			$this->aProvincia = null;
		}
		if ($this->aLocalidad !== null && $this->localidad_id !== $this->aLocalidad->getId()) {
			$this->aLocalidad = null;
		}
		if ($this->asfGuardUserRelatedByCreatedById !== null && $this->created_by_id !== $this->asfGuardUserRelatedByCreatedById->getId()) {
			$this->asfGuardUserRelatedByCreatedById = null;
		}
		if ($this->asfGuardUserRelatedByUpdatedById !== null && $this->updated_by_id !== $this->asfGuardUserRelatedByUpdatedById->getId()) {
			$this->asfGuardUserRelatedByUpdatedById = null;
		}
		if ($this->asfGuardUserRelatedByDeletedById !== null && $this->deleted_by_id !== $this->asfGuardUserRelatedByDeletedById->getId()) {
			$this->asfGuardUserRelatedByDeletedById = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DomicilioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = DomicilioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPersona = null;
			$this->aProvincia = null;
			$this->aLocalidad = null;
			$this->asfGuardUserRelatedByCreatedById = null;
			$this->asfGuardUserRelatedByUpdatedById = null;
			$this->asfGuardUserRelatedByDeletedById = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DomicilioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDomicilio:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				DomicilioPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDomicilio:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DomicilioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDomicilio:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(DomicilioPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(DomicilioPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDomicilio:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				DomicilioPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPersona !== null) {
				if ($this->aPersona->isModified() || $this->aPersona->isNew()) {
					$affectedRows += $this->aPersona->save($con);
				}
				$this->setPersona($this->aPersona);
			}

			if ($this->aProvincia !== null) {
				if ($this->aProvincia->isModified() || $this->aProvincia->isNew()) {
					$affectedRows += $this->aProvincia->save($con);
				}
				$this->setProvincia($this->aProvincia);
			}

			if ($this->aLocalidad !== null) {
				if ($this->aLocalidad->isModified() || $this->aLocalidad->isNew()) {
					$affectedRows += $this->aLocalidad->save($con);
				}
				$this->setLocalidad($this->aLocalidad);
			}

			if ($this->asfGuardUserRelatedByCreatedById !== null) {
				if ($this->asfGuardUserRelatedByCreatedById->isModified() || $this->asfGuardUserRelatedByCreatedById->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByCreatedById->save($con);
				}
				$this->setsfGuardUserRelatedByCreatedById($this->asfGuardUserRelatedByCreatedById);
			}

			if ($this->asfGuardUserRelatedByUpdatedById !== null) {
				if ($this->asfGuardUserRelatedByUpdatedById->isModified() || $this->asfGuardUserRelatedByUpdatedById->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByUpdatedById->save($con);
				}
				$this->setsfGuardUserRelatedByUpdatedById($this->asfGuardUserRelatedByUpdatedById);
			}

			if ($this->asfGuardUserRelatedByDeletedById !== null) {
				if ($this->asfGuardUserRelatedByDeletedById->isModified() || $this->asfGuardUserRelatedByDeletedById->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByDeletedById->save($con);
				}
				$this->setsfGuardUserRelatedByDeletedById($this->asfGuardUserRelatedByDeletedById);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = DomicilioPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = DomicilioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += DomicilioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPersona !== null) {
				if (!$this->aPersona->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPersona->getValidationFailures());
				}
			}

			if ($this->aProvincia !== null) {
				if (!$this->aProvincia->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProvincia->getValidationFailures());
				}
			}

			if ($this->aLocalidad !== null) {
				if (!$this->aLocalidad->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aLocalidad->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByCreatedById !== null) {
				if (!$this->asfGuardUserRelatedByCreatedById->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByCreatedById->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByUpdatedById !== null) {
				if (!$this->asfGuardUserRelatedByUpdatedById->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByUpdatedById->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByDeletedById !== null) {
				if (!$this->asfGuardUserRelatedByDeletedById->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByDeletedById->getValidationFailures());
				}
			}


			if (($retval = DomicilioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DomicilioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPersonaId();
				break;
			case 2:
				return $this->getProvinciaId();
				break;
			case 3:
				return $this->getLocalidadId();
				break;
			case 4:
				return $this->getTelefono();
				break;
			case 5:
				return $this->getCalle();
				break;
			case 6:
				return $this->getAltura();
				break;
			case 7:
				return $this->getPiso();
				break;
			case 8:
				return $this->getDpto();
				break;
			case 9:
				return $this->getCodigoPostal();
				break;
			case 10:
				return $this->getEscalera();
				break;
			case 11:
				return $this->getTorre();
				break;
			case 12:
				return $this->getNudo();
				break;
			case 13:
				return $this->getAla();
				break;
			case 14:
				return $this->getParcela();
				break;
			case 15:
				return $this->getEntreCalles();
				break;
			case 16:
				return $this->getCreatedAt();
				break;
			case 17:
				return $this->getCreatedById();
				break;
			case 18:
				return $this->getUpdatedAt();
				break;
			case 19:
				return $this->getUpdatedById();
				break;
			case 20:
				return $this->getDeletedAt();
				break;
			case 21:
				return $this->getDeletedById();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = DomicilioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPersonaId(),
			$keys[2] => $this->getProvinciaId(),
			$keys[3] => $this->getLocalidadId(),
			$keys[4] => $this->getTelefono(),
			$keys[5] => $this->getCalle(),
			$keys[6] => $this->getAltura(),
			$keys[7] => $this->getPiso(),
			$keys[8] => $this->getDpto(),
			$keys[9] => $this->getCodigoPostal(),
			$keys[10] => $this->getEscalera(),
			$keys[11] => $this->getTorre(),
			$keys[12] => $this->getNudo(),
			$keys[13] => $this->getAla(),
			$keys[14] => $this->getParcela(),
			$keys[15] => $this->getEntreCalles(),
			$keys[16] => $this->getCreatedAt(),
			$keys[17] => $this->getCreatedById(),
			$keys[18] => $this->getUpdatedAt(),
			$keys[19] => $this->getUpdatedById(),
			$keys[20] => $this->getDeletedAt(),
			$keys[21] => $this->getDeletedById(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DomicilioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPersonaId($value);
				break;
			case 2:
				$this->setProvinciaId($value);
				break;
			case 3:
				$this->setLocalidadId($value);
				break;
			case 4:
				$this->setTelefono($value);
				break;
			case 5:
				$this->setCalle($value);
				break;
			case 6:
				$this->setAltura($value);
				break;
			case 7:
				$this->setPiso($value);
				break;
			case 8:
				$this->setDpto($value);
				break;
			case 9:
				$this->setCodigoPostal($value);
				break;
			case 10:
				$this->setEscalera($value);
				break;
			case 11:
				$this->setTorre($value);
				break;
			case 12:
				$this->setNudo($value);
				break;
			case 13:
				$this->setAla($value);
				break;
			case 14:
				$this->setParcela($value);
				break;
			case 15:
				$this->setEntreCalles($value);
				break;
			case 16:
				$this->setCreatedAt($value);
				break;
			case 17:
				$this->setCreatedById($value);
				break;
			case 18:
				$this->setUpdatedAt($value);
				break;
			case 19:
				$this->setUpdatedById($value);
				break;
			case 20:
				$this->setDeletedAt($value);
				break;
			case 21:
				$this->setDeletedById($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = DomicilioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPersonaId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setProvinciaId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setLocalidadId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTelefono($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCalle($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setAltura($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPiso($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDpto($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCodigoPostal($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setEscalera($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setTorre($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setNudo($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setAla($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setParcela($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setEntreCalles($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setCreatedAt($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setCreatedById($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setUpdatedAt($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setUpdatedById($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setDeletedAt($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setDeletedById($arr[$keys[21]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(DomicilioPeer::DATABASE_NAME);

		if ($this->isColumnModified(DomicilioPeer::ID)) $criteria->add(DomicilioPeer::ID, $this->id);
		if ($this->isColumnModified(DomicilioPeer::PERSONA_ID)) $criteria->add(DomicilioPeer::PERSONA_ID, $this->persona_id);
		if ($this->isColumnModified(DomicilioPeer::PROVINCIA_ID)) $criteria->add(DomicilioPeer::PROVINCIA_ID, $this->provincia_id);
		if ($this->isColumnModified(DomicilioPeer::LOCALIDAD_ID)) $criteria->add(DomicilioPeer::LOCALIDAD_ID, $this->localidad_id);
		if ($this->isColumnModified(DomicilioPeer::TELEFONO)) $criteria->add(DomicilioPeer::TELEFONO, $this->telefono);
		if ($this->isColumnModified(DomicilioPeer::CALLE)) $criteria->add(DomicilioPeer::CALLE, $this->calle);
		if ($this->isColumnModified(DomicilioPeer::ALTURA)) $criteria->add(DomicilioPeer::ALTURA, $this->altura);
		if ($this->isColumnModified(DomicilioPeer::PISO)) $criteria->add(DomicilioPeer::PISO, $this->piso);
		if ($this->isColumnModified(DomicilioPeer::DPTO)) $criteria->add(DomicilioPeer::DPTO, $this->dpto);
		if ($this->isColumnModified(DomicilioPeer::CODIGO_POSTAL)) $criteria->add(DomicilioPeer::CODIGO_POSTAL, $this->codigo_postal);
		if ($this->isColumnModified(DomicilioPeer::ESCALERA)) $criteria->add(DomicilioPeer::ESCALERA, $this->escalera);
		if ($this->isColumnModified(DomicilioPeer::TORRE)) $criteria->add(DomicilioPeer::TORRE, $this->torre);
		if ($this->isColumnModified(DomicilioPeer::NUDO)) $criteria->add(DomicilioPeer::NUDO, $this->nudo);
		if ($this->isColumnModified(DomicilioPeer::ALA)) $criteria->add(DomicilioPeer::ALA, $this->ala);
		if ($this->isColumnModified(DomicilioPeer::PARCELA)) $criteria->add(DomicilioPeer::PARCELA, $this->parcela);
		if ($this->isColumnModified(DomicilioPeer::ENTRE_CALLES)) $criteria->add(DomicilioPeer::ENTRE_CALLES, $this->entre_calles);
		if ($this->isColumnModified(DomicilioPeer::CREATED_AT)) $criteria->add(DomicilioPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(DomicilioPeer::CREATED_BY_ID)) $criteria->add(DomicilioPeer::CREATED_BY_ID, $this->created_by_id);
		if ($this->isColumnModified(DomicilioPeer::UPDATED_AT)) $criteria->add(DomicilioPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(DomicilioPeer::UPDATED_BY_ID)) $criteria->add(DomicilioPeer::UPDATED_BY_ID, $this->updated_by_id);
		if ($this->isColumnModified(DomicilioPeer::DELETED_AT)) $criteria->add(DomicilioPeer::DELETED_AT, $this->deleted_at);
		if ($this->isColumnModified(DomicilioPeer::DELETED_BY_ID)) $criteria->add(DomicilioPeer::DELETED_BY_ID, $this->deleted_by_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(DomicilioPeer::DATABASE_NAME);

		$criteria->add(DomicilioPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Domicilio (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPersonaId($this->persona_id);

		$copyObj->setProvinciaId($this->provincia_id);

		$copyObj->setLocalidadId($this->localidad_id);

		$copyObj->setTelefono($this->telefono);

		$copyObj->setCalle($this->calle);

		$copyObj->setAltura($this->altura);

		$copyObj->setPiso($this->piso);

		$copyObj->setDpto($this->dpto);

		$copyObj->setCodigoPostal($this->codigo_postal);

		$copyObj->setEscalera($this->escalera);

		$copyObj->setTorre($this->torre);

		$copyObj->setNudo($this->nudo);

		$copyObj->setAla($this->ala);

		$copyObj->setParcela($this->parcela);

		$copyObj->setEntreCalles($this->entre_calles);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setCreatedById($this->created_by_id);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setUpdatedById($this->updated_by_id);

		$copyObj->setDeletedAt($this->deleted_at);

		$copyObj->setDeletedById($this->deleted_by_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Domicilio Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     DomicilioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new DomicilioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Persona object.
	 *
	 * @param      Persona $v
	 * @return     Domicilio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPersona(Persona $v = null)
	{
		if ($v === null) {
			$this->setPersonaId(NULL);
		} else {
			$this->setPersonaId($v->getId());
		}

		$this->aPersona = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Persona object, it will not be re-added.
		if ($v !== null) {
			$v->addDomicilio($this);
		}

		return $this;
	}


	/**
	 * Get the associated Persona object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Persona The associated Persona object.
	 * @throws     PropelException
	 */
	public function getPersona(PropelPDO $con = null)
	{
		if ($this->aPersona === null && ($this->persona_id !== null)) {
			$this->aPersona = PersonaPeer::retrieveByPk($this->persona_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPersona->addDomicilios($this);
			 */
		}
		return $this->aPersona;
	}

	/**
	 * Declares an association between this object and a Provincia object.
	 *
	 * @param      Provincia $v
	 * @return     Domicilio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProvincia(Provincia $v = null)
	{
		if ($v === null) {
			$this->setProvinciaId(NULL);
		} else {
			$this->setProvinciaId($v->getId());
		}

		$this->aProvincia = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Provincia object, it will not be re-added.
		if ($v !== null) {
			$v->addDomicilio($this);
		}

		return $this;
	}


	/**
	 * Get the associated Provincia object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Provincia The associated Provincia object.
	 * @throws     PropelException
	 */
	public function getProvincia(PropelPDO $con = null)
	{
		if ($this->aProvincia === null && ($this->provincia_id !== null)) {
			$this->aProvincia = ProvinciaPeer::retrieveByPk($this->provincia_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProvincia->addDomicilios($this);
			 */
		}
		return $this->aProvincia;
	}

	/**
	 * Declares an association between this object and a Localidad object.
	 *
	 * @param      Localidad $v
	 * @return     Domicilio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setLocalidad(Localidad $v = null)
	{
		if ($v === null) {
			$this->setLocalidadId(NULL);
		} else {
			$this->setLocalidadId($v->getId());
		}

		$this->aLocalidad = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Localidad object, it will not be re-added.
		if ($v !== null) {
			$v->addDomicilio($this);
		}

		return $this;
	}


	/**
	 * Get the associated Localidad object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Localidad The associated Localidad object.
	 * @throws     PropelException
	 */
	public function getLocalidad(PropelPDO $con = null)
	{
		if ($this->aLocalidad === null && ($this->localidad_id !== null)) {
			$this->aLocalidad = LocalidadPeer::retrieveByPk($this->localidad_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aLocalidad->addDomicilios($this);
			 */
		}
		return $this->aLocalidad;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Domicilio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByCreatedById(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setCreatedById(NULL);
		} else {
			$this->setCreatedById($v->getId());
		}

		$this->asfGuardUserRelatedByCreatedById = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addDomicilioRelatedByCreatedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByCreatedById(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByCreatedById === null && ($this->created_by_id !== null)) {
			$this->asfGuardUserRelatedByCreatedById = sfGuardUserPeer::retrieveByPk($this->created_by_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByCreatedById->addDomiciliosRelatedByCreatedById($this);
			 */
		}
		return $this->asfGuardUserRelatedByCreatedById;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Domicilio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByUpdatedById(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUpdatedById(NULL);
		} else {
			$this->setUpdatedById($v->getId());
		}

		$this->asfGuardUserRelatedByUpdatedById = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addDomicilioRelatedByUpdatedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByUpdatedById(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByUpdatedById === null && ($this->updated_by_id !== null)) {
			$this->asfGuardUserRelatedByUpdatedById = sfGuardUserPeer::retrieveByPk($this->updated_by_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByUpdatedById->addDomiciliosRelatedByUpdatedById($this);
			 */
		}
		return $this->asfGuardUserRelatedByUpdatedById;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Domicilio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByDeletedById(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setDeletedById(NULL);
		} else {
			$this->setDeletedById($v->getId());
		}

		$this->asfGuardUserRelatedByDeletedById = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addDomicilioRelatedByDeletedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByDeletedById(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByDeletedById === null && ($this->deleted_by_id !== null)) {
			$this->asfGuardUserRelatedByDeletedById = sfGuardUserPeer::retrieveByPk($this->deleted_by_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByDeletedById->addDomiciliosRelatedByDeletedById($this);
			 */
		}
		return $this->asfGuardUserRelatedByDeletedById;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aPersona = null;
			$this->aProvincia = null;
			$this->aLocalidad = null;
			$this->asfGuardUserRelatedByCreatedById = null;
			$this->asfGuardUserRelatedByUpdatedById = null;
			$this->asfGuardUserRelatedByDeletedById = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseDomicilio:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseDomicilio::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseDomicilio
