<?php

/**
 * Base class that represents a row from the 'empleo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Oct 20 15:57:46 2012
 *
 * @package    lib.model.om
 */
abstract class BaseEmpleo extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EmpleoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the persona_id field.
	 * @var        int
	 */
	protected $persona_id;

	/**
	 * The value for the tipo_empleo_id field.
	 * @var        int
	 */
	protected $tipo_empleo_id;

	/**
	 * The value for the cuit field.
	 * @var        int
	 */
	protected $cuit;

	/**
	 * The value for the fecha_inicio field.
	 * @var        string
	 */
	protected $fecha_inicio;

	/**
	 * The value for the fecha_fin field.
	 * @var        string
	 */
	protected $fecha_fin;

	/**
	 * The value for the cargo field.
	 * @var        string
	 */
	protected $cargo;

	/**
	 * The value for the lugar_trabajo field.
	 * @var        string
	 */
	protected $lugar_trabajo;

	/**
	 * The value for the telefono field.
	 * @var        string
	 */
	protected $telefono;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the created_by_id field.
	 * @var        int
	 */
	protected $created_by_id;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the updated_by_id field.
	 * @var        int
	 */
	protected $updated_by_id;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * The value for the deleted_by_id field.
	 * @var        int
	 */
	protected $deleted_by_id;

	/**
	 * @var        Persona
	 */
	protected $aPersona;

	/**
	 * @var        TipoEmpleo
	 */
	protected $aTipoEmpleo;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByCreatedById;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByUpdatedById;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByDeletedById;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'EmpleoPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [persona_id] column value.
	 * 
	 * @return     int
	 */
	public function getPersonaId()
	{
		return $this->persona_id;
	}

	/**
	 * Get the [tipo_empleo_id] column value.
	 * 
	 * @return     int
	 */
	public function getTipoEmpleoId()
	{
		return $this->tipo_empleo_id;
	}

	/**
	 * Get the [cuit] column value.
	 * 
	 * @return     int
	 */
	public function getCuit()
	{
		return $this->cuit;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_inicio] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaInicio($format = 'Y-m-d')
	{
		if ($this->fecha_inicio === null) {
			return null;
		}


		if ($this->fecha_inicio === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_inicio);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_inicio, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_fin] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaFin($format = 'Y-m-d')
	{
		if ($this->fecha_fin === null) {
			return null;
		}


		if ($this->fecha_fin === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_fin);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_fin, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [cargo] column value.
	 * 
	 * @return     string
	 */
	public function getCargo()
	{
		return $this->cargo;
	}

	/**
	 * Get the [lugar_trabajo] column value.
	 * 
	 * @return     string
	 */
	public function getLugarTrabajo()
	{
		return $this->lugar_trabajo;
	}

	/**
	 * Get the [telefono] column value.
	 * 
	 * @return     string
	 */
	public function getTelefono()
	{
		return $this->telefono;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [created_by_id] column value.
	 * 
	 * @return     int
	 */
	public function getCreatedById()
	{
		return $this->created_by_id;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [updated_by_id] column value.
	 * 
	 * @return     int
	 */
	public function getUpdatedById()
	{
		return $this->updated_by_id;
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}


		if ($this->deleted_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->deleted_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [deleted_by_id] column value.
	 * 
	 * @return     int
	 */
	public function getDeletedById()
	{
		return $this->deleted_by_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EmpleoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [persona_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setPersonaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->persona_id !== $v) {
			$this->persona_id = $v;
			$this->modifiedColumns[] = EmpleoPeer::PERSONA_ID;
		}

		if ($this->aPersona !== null && $this->aPersona->getId() !== $v) {
			$this->aPersona = null;
		}

		return $this;
	} // setPersonaId()

	/**
	 * Set the value of [tipo_empleo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setTipoEmpleoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tipo_empleo_id !== $v) {
			$this->tipo_empleo_id = $v;
			$this->modifiedColumns[] = EmpleoPeer::TIPO_EMPLEO_ID;
		}

		if ($this->aTipoEmpleo !== null && $this->aTipoEmpleo->getId() !== $v) {
			$this->aTipoEmpleo = null;
		}

		return $this;
	} // setTipoEmpleoId()

	/**
	 * Set the value of [cuit] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setCuit($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cuit !== $v) {
			$this->cuit = $v;
			$this->modifiedColumns[] = EmpleoPeer::CUIT;
		}

		return $this;
	} // setCuit()

	/**
	 * Sets the value of [fecha_inicio] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setFechaInicio($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_inicio !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_inicio !== null && $tmpDt = new DateTime($this->fecha_inicio)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_inicio = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = EmpleoPeer::FECHA_INICIO;
			}
		} // if either are not null

		return $this;
	} // setFechaInicio()

	/**
	 * Sets the value of [fecha_fin] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setFechaFin($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_fin !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_fin !== null && $tmpDt = new DateTime($this->fecha_fin)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_fin = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = EmpleoPeer::FECHA_FIN;
			}
		} // if either are not null

		return $this;
	} // setFechaFin()

	/**
	 * Set the value of [cargo] column.
	 * 
	 * @param      string $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setCargo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cargo !== $v) {
			$this->cargo = $v;
			$this->modifiedColumns[] = EmpleoPeer::CARGO;
		}

		return $this;
	} // setCargo()

	/**
	 * Set the value of [lugar_trabajo] column.
	 * 
	 * @param      string $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setLugarTrabajo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lugar_trabajo !== $v) {
			$this->lugar_trabajo = $v;
			$this->modifiedColumns[] = EmpleoPeer::LUGAR_TRABAJO;
		}

		return $this;
	} // setLugarTrabajo()

	/**
	 * Set the value of [telefono] column.
	 * 
	 * @param      string $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setTelefono($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono !== $v) {
			$this->telefono = $v;
			$this->modifiedColumns[] = EmpleoPeer::TELEFONO;
		}

		return $this;
	} // setTelefono()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EmpleoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [created_by_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setCreatedById($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->created_by_id !== $v) {
			$this->created_by_id = $v;
			$this->modifiedColumns[] = EmpleoPeer::CREATED_BY_ID;
		}

		if ($this->asfGuardUserRelatedByCreatedById !== null && $this->asfGuardUserRelatedByCreatedById->getId() !== $v) {
			$this->asfGuardUserRelatedByCreatedById = null;
		}

		return $this;
	} // setCreatedById()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EmpleoPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [updated_by_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setUpdatedById($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->updated_by_id !== $v) {
			$this->updated_by_id = $v;
			$this->modifiedColumns[] = EmpleoPeer::UPDATED_BY_ID;
		}

		if ($this->asfGuardUserRelatedByUpdatedById !== null && $this->asfGuardUserRelatedByUpdatedById->getId() !== $v) {
			$this->asfGuardUserRelatedByUpdatedById = null;
		}

		return $this;
	} // setUpdatedById()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deleted_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deleted_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EmpleoPeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Set the value of [deleted_by_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empleo The current object (for fluent API support)
	 */
	public function setDeletedById($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->deleted_by_id !== $v) {
			$this->deleted_by_id = $v;
			$this->modifiedColumns[] = EmpleoPeer::DELETED_BY_ID;
		}

		if ($this->asfGuardUserRelatedByDeletedById !== null && $this->asfGuardUserRelatedByDeletedById->getId() !== $v) {
			$this->asfGuardUserRelatedByDeletedById = null;
		}

		return $this;
	} // setDeletedById()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->persona_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->tipo_empleo_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->cuit = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->fecha_inicio = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fecha_fin = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->cargo = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->lugar_trabajo = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->telefono = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->created_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->created_by_id = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->updated_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->updated_by_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->deleted_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->deleted_by_id = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = EmpleoPeer::NUM_COLUMNS - EmpleoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Empleo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPersona !== null && $this->persona_id !== $this->aPersona->getId()) {
			$this->aPersona = null;
		}
		if ($this->aTipoEmpleo !== null && $this->tipo_empleo_id !== $this->aTipoEmpleo->getId()) {
			$this->aTipoEmpleo = null;
		}
		if ($this->asfGuardUserRelatedByCreatedById !== null && $this->created_by_id !== $this->asfGuardUserRelatedByCreatedById->getId()) {
			$this->asfGuardUserRelatedByCreatedById = null;
		}
		if ($this->asfGuardUserRelatedByUpdatedById !== null && $this->updated_by_id !== $this->asfGuardUserRelatedByUpdatedById->getId()) {
			$this->asfGuardUserRelatedByUpdatedById = null;
		}
		if ($this->asfGuardUserRelatedByDeletedById !== null && $this->deleted_by_id !== $this->asfGuardUserRelatedByDeletedById->getId()) {
			$this->asfGuardUserRelatedByDeletedById = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EmpleoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EmpleoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPersona = null;
			$this->aTipoEmpleo = null;
			$this->asfGuardUserRelatedByCreatedById = null;
			$this->asfGuardUserRelatedByUpdatedById = null;
			$this->asfGuardUserRelatedByDeletedById = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EmpleoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEmpleo:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				EmpleoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEmpleo:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EmpleoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEmpleo:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(EmpleoPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(EmpleoPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEmpleo:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				EmpleoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPersona !== null) {
				if ($this->aPersona->isModified() || $this->aPersona->isNew()) {
					$affectedRows += $this->aPersona->save($con);
				}
				$this->setPersona($this->aPersona);
			}

			if ($this->aTipoEmpleo !== null) {
				if ($this->aTipoEmpleo->isModified() || $this->aTipoEmpleo->isNew()) {
					$affectedRows += $this->aTipoEmpleo->save($con);
				}
				$this->setTipoEmpleo($this->aTipoEmpleo);
			}

			if ($this->asfGuardUserRelatedByCreatedById !== null) {
				if ($this->asfGuardUserRelatedByCreatedById->isModified() || $this->asfGuardUserRelatedByCreatedById->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByCreatedById->save($con);
				}
				$this->setsfGuardUserRelatedByCreatedById($this->asfGuardUserRelatedByCreatedById);
			}

			if ($this->asfGuardUserRelatedByUpdatedById !== null) {
				if ($this->asfGuardUserRelatedByUpdatedById->isModified() || $this->asfGuardUserRelatedByUpdatedById->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByUpdatedById->save($con);
				}
				$this->setsfGuardUserRelatedByUpdatedById($this->asfGuardUserRelatedByUpdatedById);
			}

			if ($this->asfGuardUserRelatedByDeletedById !== null) {
				if ($this->asfGuardUserRelatedByDeletedById->isModified() || $this->asfGuardUserRelatedByDeletedById->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByDeletedById->save($con);
				}
				$this->setsfGuardUserRelatedByDeletedById($this->asfGuardUserRelatedByDeletedById);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EmpleoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EmpleoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EmpleoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPersona !== null) {
				if (!$this->aPersona->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPersona->getValidationFailures());
				}
			}

			if ($this->aTipoEmpleo !== null) {
				if (!$this->aTipoEmpleo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipoEmpleo->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByCreatedById !== null) {
				if (!$this->asfGuardUserRelatedByCreatedById->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByCreatedById->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByUpdatedById !== null) {
				if (!$this->asfGuardUserRelatedByUpdatedById->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByUpdatedById->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByDeletedById !== null) {
				if (!$this->asfGuardUserRelatedByDeletedById->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByDeletedById->getValidationFailures());
				}
			}


			if (($retval = EmpleoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EmpleoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPersonaId();
				break;
			case 2:
				return $this->getTipoEmpleoId();
				break;
			case 3:
				return $this->getCuit();
				break;
			case 4:
				return $this->getFechaInicio();
				break;
			case 5:
				return $this->getFechaFin();
				break;
			case 6:
				return $this->getCargo();
				break;
			case 7:
				return $this->getLugarTrabajo();
				break;
			case 8:
				return $this->getTelefono();
				break;
			case 9:
				return $this->getCreatedAt();
				break;
			case 10:
				return $this->getCreatedById();
				break;
			case 11:
				return $this->getUpdatedAt();
				break;
			case 12:
				return $this->getUpdatedById();
				break;
			case 13:
				return $this->getDeletedAt();
				break;
			case 14:
				return $this->getDeletedById();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EmpleoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPersonaId(),
			$keys[2] => $this->getTipoEmpleoId(),
			$keys[3] => $this->getCuit(),
			$keys[4] => $this->getFechaInicio(),
			$keys[5] => $this->getFechaFin(),
			$keys[6] => $this->getCargo(),
			$keys[7] => $this->getLugarTrabajo(),
			$keys[8] => $this->getTelefono(),
			$keys[9] => $this->getCreatedAt(),
			$keys[10] => $this->getCreatedById(),
			$keys[11] => $this->getUpdatedAt(),
			$keys[12] => $this->getUpdatedById(),
			$keys[13] => $this->getDeletedAt(),
			$keys[14] => $this->getDeletedById(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EmpleoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPersonaId($value);
				break;
			case 2:
				$this->setTipoEmpleoId($value);
				break;
			case 3:
				$this->setCuit($value);
				break;
			case 4:
				$this->setFechaInicio($value);
				break;
			case 5:
				$this->setFechaFin($value);
				break;
			case 6:
				$this->setCargo($value);
				break;
			case 7:
				$this->setLugarTrabajo($value);
				break;
			case 8:
				$this->setTelefono($value);
				break;
			case 9:
				$this->setCreatedAt($value);
				break;
			case 10:
				$this->setCreatedById($value);
				break;
			case 11:
				$this->setUpdatedAt($value);
				break;
			case 12:
				$this->setUpdatedById($value);
				break;
			case 13:
				$this->setDeletedAt($value);
				break;
			case 14:
				$this->setDeletedById($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EmpleoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPersonaId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTipoEmpleoId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCuit($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFechaInicio($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFechaFin($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCargo($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setLugarTrabajo($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTelefono($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCreatedAt($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCreatedById($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUpdatedAt($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUpdatedById($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setDeletedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setDeletedById($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EmpleoPeer::DATABASE_NAME);

		if ($this->isColumnModified(EmpleoPeer::ID)) $criteria->add(EmpleoPeer::ID, $this->id);
		if ($this->isColumnModified(EmpleoPeer::PERSONA_ID)) $criteria->add(EmpleoPeer::PERSONA_ID, $this->persona_id);
		if ($this->isColumnModified(EmpleoPeer::TIPO_EMPLEO_ID)) $criteria->add(EmpleoPeer::TIPO_EMPLEO_ID, $this->tipo_empleo_id);
		if ($this->isColumnModified(EmpleoPeer::CUIT)) $criteria->add(EmpleoPeer::CUIT, $this->cuit);
		if ($this->isColumnModified(EmpleoPeer::FECHA_INICIO)) $criteria->add(EmpleoPeer::FECHA_INICIO, $this->fecha_inicio);
		if ($this->isColumnModified(EmpleoPeer::FECHA_FIN)) $criteria->add(EmpleoPeer::FECHA_FIN, $this->fecha_fin);
		if ($this->isColumnModified(EmpleoPeer::CARGO)) $criteria->add(EmpleoPeer::CARGO, $this->cargo);
		if ($this->isColumnModified(EmpleoPeer::LUGAR_TRABAJO)) $criteria->add(EmpleoPeer::LUGAR_TRABAJO, $this->lugar_trabajo);
		if ($this->isColumnModified(EmpleoPeer::TELEFONO)) $criteria->add(EmpleoPeer::TELEFONO, $this->telefono);
		if ($this->isColumnModified(EmpleoPeer::CREATED_AT)) $criteria->add(EmpleoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(EmpleoPeer::CREATED_BY_ID)) $criteria->add(EmpleoPeer::CREATED_BY_ID, $this->created_by_id);
		if ($this->isColumnModified(EmpleoPeer::UPDATED_AT)) $criteria->add(EmpleoPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(EmpleoPeer::UPDATED_BY_ID)) $criteria->add(EmpleoPeer::UPDATED_BY_ID, $this->updated_by_id);
		if ($this->isColumnModified(EmpleoPeer::DELETED_AT)) $criteria->add(EmpleoPeer::DELETED_AT, $this->deleted_at);
		if ($this->isColumnModified(EmpleoPeer::DELETED_BY_ID)) $criteria->add(EmpleoPeer::DELETED_BY_ID, $this->deleted_by_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EmpleoPeer::DATABASE_NAME);

		$criteria->add(EmpleoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Empleo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPersonaId($this->persona_id);

		$copyObj->setTipoEmpleoId($this->tipo_empleo_id);

		$copyObj->setCuit($this->cuit);

		$copyObj->setFechaInicio($this->fecha_inicio);

		$copyObj->setFechaFin($this->fecha_fin);

		$copyObj->setCargo($this->cargo);

		$copyObj->setLugarTrabajo($this->lugar_trabajo);

		$copyObj->setTelefono($this->telefono);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setCreatedById($this->created_by_id);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setUpdatedById($this->updated_by_id);

		$copyObj->setDeletedAt($this->deleted_at);

		$copyObj->setDeletedById($this->deleted_by_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Empleo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EmpleoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EmpleoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Persona object.
	 *
	 * @param      Persona $v
	 * @return     Empleo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPersona(Persona $v = null)
	{
		if ($v === null) {
			$this->setPersonaId(NULL);
		} else {
			$this->setPersonaId($v->getId());
		}

		$this->aPersona = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Persona object, it will not be re-added.
		if ($v !== null) {
			$v->addEmpleo($this);
		}

		return $this;
	}


	/**
	 * Get the associated Persona object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Persona The associated Persona object.
	 * @throws     PropelException
	 */
	public function getPersona(PropelPDO $con = null)
	{
		if ($this->aPersona === null && ($this->persona_id !== null)) {
			$this->aPersona = PersonaPeer::retrieveByPk($this->persona_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPersona->addEmpleos($this);
			 */
		}
		return $this->aPersona;
	}

	/**
	 * Declares an association between this object and a TipoEmpleo object.
	 *
	 * @param      TipoEmpleo $v
	 * @return     Empleo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipoEmpleo(TipoEmpleo $v = null)
	{
		if ($v === null) {
			$this->setTipoEmpleoId(NULL);
		} else {
			$this->setTipoEmpleoId($v->getId());
		}

		$this->aTipoEmpleo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TipoEmpleo object, it will not be re-added.
		if ($v !== null) {
			$v->addEmpleo($this);
		}

		return $this;
	}


	/**
	 * Get the associated TipoEmpleo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TipoEmpleo The associated TipoEmpleo object.
	 * @throws     PropelException
	 */
	public function getTipoEmpleo(PropelPDO $con = null)
	{
		if ($this->aTipoEmpleo === null && ($this->tipo_empleo_id !== null)) {
			$this->aTipoEmpleo = TipoEmpleoPeer::retrieveByPk($this->tipo_empleo_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTipoEmpleo->addEmpleos($this);
			 */
		}
		return $this->aTipoEmpleo;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Empleo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByCreatedById(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setCreatedById(NULL);
		} else {
			$this->setCreatedById($v->getId());
		}

		$this->asfGuardUserRelatedByCreatedById = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addEmpleoRelatedByCreatedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByCreatedById(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByCreatedById === null && ($this->created_by_id !== null)) {
			$this->asfGuardUserRelatedByCreatedById = sfGuardUserPeer::retrieveByPk($this->created_by_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByCreatedById->addEmpleosRelatedByCreatedById($this);
			 */
		}
		return $this->asfGuardUserRelatedByCreatedById;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Empleo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByUpdatedById(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUpdatedById(NULL);
		} else {
			$this->setUpdatedById($v->getId());
		}

		$this->asfGuardUserRelatedByUpdatedById = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addEmpleoRelatedByUpdatedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByUpdatedById(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByUpdatedById === null && ($this->updated_by_id !== null)) {
			$this->asfGuardUserRelatedByUpdatedById = sfGuardUserPeer::retrieveByPk($this->updated_by_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByUpdatedById->addEmpleosRelatedByUpdatedById($this);
			 */
		}
		return $this->asfGuardUserRelatedByUpdatedById;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Empleo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByDeletedById(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setDeletedById(NULL);
		} else {
			$this->setDeletedById($v->getId());
		}

		$this->asfGuardUserRelatedByDeletedById = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addEmpleoRelatedByDeletedById($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByDeletedById(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByDeletedById === null && ($this->deleted_by_id !== null)) {
			$this->asfGuardUserRelatedByDeletedById = sfGuardUserPeer::retrieveByPk($this->deleted_by_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByDeletedById->addEmpleosRelatedByDeletedById($this);
			 */
		}
		return $this->asfGuardUserRelatedByDeletedById;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aPersona = null;
			$this->aTipoEmpleo = null;
			$this->asfGuardUserRelatedByCreatedById = null;
			$this->asfGuardUserRelatedByUpdatedById = null;
			$this->asfGuardUserRelatedByDeletedById = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseEmpleo:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseEmpleo::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseEmpleo
