<?php

/**
 * Base class that represents a row from the 'estado_civil' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:16 2012
 *
 * @package    lib.model.om
 */
abstract class BaseEstadoCivil extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EstadoCivilPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the user_created field.
	 * @var        int
	 */
	protected $user_created;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the user_updated field.
	 * @var        int
	 */
	protected $user_updated;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * The value for the user_deleted field.
	 * @var        int
	 */
	protected $user_deleted;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUserCreated;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUserUpdated;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUserDeleted;

	/**
	 * @var        array Persona[] Collection to store aggregation of Persona objects.
	 */
	protected $collPersonas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPersonas.
	 */
	private $lastPersonaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'EstadoCivilPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [user_created] column value.
	 * 
	 * @return     int
	 */
	public function getUserCreated()
	{
		return $this->user_created;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [user_updated] column value.
	 * 
	 * @return     int
	 */
	public function getUserUpdated()
	{
		return $this->user_updated;
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}


		if ($this->deleted_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->deleted_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [user_deleted] column value.
	 * 
	 * @return     int
	 */
	public function getUserDeleted()
	{
		return $this->user_deleted;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EstadoCivilPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = EstadoCivilPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EstadoCivilPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [user_created] column.
	 * 
	 * @param      int $v new value
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setUserCreated($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_created !== $v) {
			$this->user_created = $v;
			$this->modifiedColumns[] = EstadoCivilPeer::USER_CREATED;
		}

		if ($this->aUsuarioRelatedByUserCreated !== null && $this->aUsuarioRelatedByUserCreated->getId() !== $v) {
			$this->aUsuarioRelatedByUserCreated = null;
		}

		return $this;
	} // setUserCreated()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EstadoCivilPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [user_updated] column.
	 * 
	 * @param      int $v new value
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setUserUpdated($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_updated !== $v) {
			$this->user_updated = $v;
			$this->modifiedColumns[] = EstadoCivilPeer::USER_UPDATED;
		}

		if ($this->aUsuarioRelatedByUserUpdated !== null && $this->aUsuarioRelatedByUserUpdated->getId() !== $v) {
			$this->aUsuarioRelatedByUserUpdated = null;
		}

		return $this;
	} // setUserUpdated()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deleted_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deleted_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EstadoCivilPeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Set the value of [user_deleted] column.
	 * 
	 * @param      int $v new value
	 * @return     EstadoCivil The current object (for fluent API support)
	 */
	public function setUserDeleted($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_deleted !== $v) {
			$this->user_deleted = $v;
			$this->modifiedColumns[] = EstadoCivilPeer::USER_DELETED;
		}

		if ($this->aUsuarioRelatedByUserDeleted !== null && $this->aUsuarioRelatedByUserDeleted->getId() !== $v) {
			$this->aUsuarioRelatedByUserDeleted = null;
		}

		return $this;
	} // setUserDeleted()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->descripcion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->created_at = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->user_created = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->updated_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->user_updated = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->deleted_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->user_deleted = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = EstadoCivilPeer::NUM_COLUMNS - EstadoCivilPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating EstadoCivil object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsuarioRelatedByUserCreated !== null && $this->user_created !== $this->aUsuarioRelatedByUserCreated->getId()) {
			$this->aUsuarioRelatedByUserCreated = null;
		}
		if ($this->aUsuarioRelatedByUserUpdated !== null && $this->user_updated !== $this->aUsuarioRelatedByUserUpdated->getId()) {
			$this->aUsuarioRelatedByUserUpdated = null;
		}
		if ($this->aUsuarioRelatedByUserDeleted !== null && $this->user_deleted !== $this->aUsuarioRelatedByUserDeleted->getId()) {
			$this->aUsuarioRelatedByUserDeleted = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EstadoCivilPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EstadoCivilPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsuarioRelatedByUserCreated = null;
			$this->aUsuarioRelatedByUserUpdated = null;
			$this->aUsuarioRelatedByUserDeleted = null;
			$this->collPersonas = null;
			$this->lastPersonaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EstadoCivilPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEstadoCivil:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				EstadoCivilPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEstadoCivil:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EstadoCivilPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEstadoCivil:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(EstadoCivilPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(EstadoCivilPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEstadoCivil:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				EstadoCivilPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuarioRelatedByUserCreated !== null) {
				if ($this->aUsuarioRelatedByUserCreated->isModified() || $this->aUsuarioRelatedByUserCreated->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUserCreated->save($con);
				}
				$this->setUsuarioRelatedByUserCreated($this->aUsuarioRelatedByUserCreated);
			}

			if ($this->aUsuarioRelatedByUserUpdated !== null) {
				if ($this->aUsuarioRelatedByUserUpdated->isModified() || $this->aUsuarioRelatedByUserUpdated->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUserUpdated->save($con);
				}
				$this->setUsuarioRelatedByUserUpdated($this->aUsuarioRelatedByUserUpdated);
			}

			if ($this->aUsuarioRelatedByUserDeleted !== null) {
				if ($this->aUsuarioRelatedByUserDeleted->isModified() || $this->aUsuarioRelatedByUserDeleted->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUserDeleted->save($con);
				}
				$this->setUsuarioRelatedByUserDeleted($this->aUsuarioRelatedByUserDeleted);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EstadoCivilPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EstadoCivilPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EstadoCivilPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPersonas !== null) {
				foreach ($this->collPersonas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuarioRelatedByUserCreated !== null) {
				if (!$this->aUsuarioRelatedByUserCreated->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUserCreated->getValidationFailures());
				}
			}

			if ($this->aUsuarioRelatedByUserUpdated !== null) {
				if (!$this->aUsuarioRelatedByUserUpdated->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUserUpdated->getValidationFailures());
				}
			}

			if ($this->aUsuarioRelatedByUserDeleted !== null) {
				if (!$this->aUsuarioRelatedByUserDeleted->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUserDeleted->getValidationFailures());
				}
			}


			if (($retval = EstadoCivilPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPersonas !== null) {
					foreach ($this->collPersonas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EstadoCivilPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getDescripcion();
				break;
			case 2:
				return $this->getCreatedAt();
				break;
			case 3:
				return $this->getUserCreated();
				break;
			case 4:
				return $this->getUpdatedAt();
				break;
			case 5:
				return $this->getUserUpdated();
				break;
			case 6:
				return $this->getDeletedAt();
				break;
			case 7:
				return $this->getUserDeleted();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EstadoCivilPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getDescripcion(),
			$keys[2] => $this->getCreatedAt(),
			$keys[3] => $this->getUserCreated(),
			$keys[4] => $this->getUpdatedAt(),
			$keys[5] => $this->getUserUpdated(),
			$keys[6] => $this->getDeletedAt(),
			$keys[7] => $this->getUserDeleted(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EstadoCivilPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setDescripcion($value);
				break;
			case 2:
				$this->setCreatedAt($value);
				break;
			case 3:
				$this->setUserCreated($value);
				break;
			case 4:
				$this->setUpdatedAt($value);
				break;
			case 5:
				$this->setUserUpdated($value);
				break;
			case 6:
				$this->setDeletedAt($value);
				break;
			case 7:
				$this->setUserDeleted($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EstadoCivilPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDescripcion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCreatedAt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUserCreated($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUpdatedAt($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUserUpdated($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDeletedAt($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUserDeleted($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);

		if ($this->isColumnModified(EstadoCivilPeer::ID)) $criteria->add(EstadoCivilPeer::ID, $this->id);
		if ($this->isColumnModified(EstadoCivilPeer::DESCRIPCION)) $criteria->add(EstadoCivilPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(EstadoCivilPeer::CREATED_AT)) $criteria->add(EstadoCivilPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(EstadoCivilPeer::USER_CREATED)) $criteria->add(EstadoCivilPeer::USER_CREATED, $this->user_created);
		if ($this->isColumnModified(EstadoCivilPeer::UPDATED_AT)) $criteria->add(EstadoCivilPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(EstadoCivilPeer::USER_UPDATED)) $criteria->add(EstadoCivilPeer::USER_UPDATED, $this->user_updated);
		if ($this->isColumnModified(EstadoCivilPeer::DELETED_AT)) $criteria->add(EstadoCivilPeer::DELETED_AT, $this->deleted_at);
		if ($this->isColumnModified(EstadoCivilPeer::USER_DELETED)) $criteria->add(EstadoCivilPeer::USER_DELETED, $this->user_deleted);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);

		$criteria->add(EstadoCivilPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of EstadoCivil (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUserCreated($this->user_created);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setUserUpdated($this->user_updated);

		$copyObj->setDeletedAt($this->deleted_at);

		$copyObj->setUserDeleted($this->user_deleted);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPersonas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPersona($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     EstadoCivil Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EstadoCivilPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EstadoCivilPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     EstadoCivil The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUserCreated(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUserCreated(NULL);
		} else {
			$this->setUserCreated($v->getId());
		}

		$this->aUsuarioRelatedByUserCreated = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addEstadoCivilRelatedByUserCreated($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUserCreated(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUserCreated === null && ($this->user_created !== null)) {
			$this->aUsuarioRelatedByUserCreated = UsuarioPeer::retrieveByPk($this->user_created);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUserCreated->addEstadoCivilsRelatedByUserCreated($this);
			 */
		}
		return $this->aUsuarioRelatedByUserCreated;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     EstadoCivil The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUserUpdated(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUserUpdated(NULL);
		} else {
			$this->setUserUpdated($v->getId());
		}

		$this->aUsuarioRelatedByUserUpdated = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addEstadoCivilRelatedByUserUpdated($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUserUpdated(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUserUpdated === null && ($this->user_updated !== null)) {
			$this->aUsuarioRelatedByUserUpdated = UsuarioPeer::retrieveByPk($this->user_updated);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUserUpdated->addEstadoCivilsRelatedByUserUpdated($this);
			 */
		}
		return $this->aUsuarioRelatedByUserUpdated;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     EstadoCivil The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUserDeleted(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUserDeleted(NULL);
		} else {
			$this->setUserDeleted($v->getId());
		}

		$this->aUsuarioRelatedByUserDeleted = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addEstadoCivilRelatedByUserDeleted($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUserDeleted(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUserDeleted === null && ($this->user_deleted !== null)) {
			$this->aUsuarioRelatedByUserDeleted = UsuarioPeer::retrieveByPk($this->user_deleted);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUserDeleted->addEstadoCivilsRelatedByUserDeleted($this);
			 */
		}
		return $this->aUsuarioRelatedByUserDeleted;
	}

	/**
	 * Clears out the collPersonas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPersonas()
	 */
	public function clearPersonas()
	{
		$this->collPersonas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPersonas collection (array).
	 *
	 * By default this just sets the collPersonas collection to an empty array (like clearcollPersonas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPersonas()
	{
		$this->collPersonas = array();
	}

	/**
	 * Gets an array of Persona objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EstadoCivil has previously been saved, it will retrieve
	 * related Personas from storage. If this EstadoCivil is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Persona[]
	 * @throws     PropelException
	 */
	public function getPersonas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
			   $this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				PersonaPeer::addSelectColumns($criteria);
				$this->collPersonas = PersonaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				PersonaPeer::addSelectColumns($criteria);
				if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
					$this->collPersonas = PersonaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPersonaCriteria = $criteria;
		return $this->collPersonas;
	}

	/**
	 * Returns the number of related Persona objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Persona objects.
	 * @throws     PropelException
	 */
	public function countPersonas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$count = PersonaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
					$count = PersonaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPersonas);
				}
			} else {
				$count = count($this->collPersonas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Persona object to this object
	 * through the Persona foreign key attribute.
	 *
	 * @param      Persona $l Persona
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPersona(Persona $l)
	{
		if ($this->collPersonas === null) {
			$this->initPersonas();
		}
		if (!in_array($l, $this->collPersonas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPersonas, $l);
			$l->setEstadoCivil($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EstadoCivil is new, it will return
	 * an empty collection; or if this EstadoCivil has previously
	 * been saved, it will retrieve related Personas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EstadoCivil.
	 */
	public function getPersonasJoinTipoDocumento($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$this->collPersonas = PersonaPeer::doSelectJoinTipoDocumento($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

			if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
				$this->collPersonas = PersonaPeer::doSelectJoinTipoDocumento($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersonaCriteria = $criteria;

		return $this->collPersonas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EstadoCivil is new, it will return
	 * an empty collection; or if this EstadoCivil has previously
	 * been saved, it will retrieve related Personas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EstadoCivil.
	 */
	public function getPersonasJoinTipoSexo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$this->collPersonas = PersonaPeer::doSelectJoinTipoSexo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

			if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
				$this->collPersonas = PersonaPeer::doSelectJoinTipoSexo($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersonaCriteria = $criteria;

		return $this->collPersonas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EstadoCivil is new, it will return
	 * an empty collection; or if this EstadoCivil has previously
	 * been saved, it will retrieve related Personas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EstadoCivil.
	 */
	public function getPersonasJoinNacionalidad($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$this->collPersonas = PersonaPeer::doSelectJoinNacionalidad($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

			if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
				$this->collPersonas = PersonaPeer::doSelectJoinNacionalidad($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersonaCriteria = $criteria;

		return $this->collPersonas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EstadoCivil is new, it will return
	 * an empty collection; or if this EstadoCivil has previously
	 * been saved, it will retrieve related Personas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EstadoCivil.
	 */
	public function getPersonasJoinUsuarioRelatedByUserCreated($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$this->collPersonas = PersonaPeer::doSelectJoinUsuarioRelatedByUserCreated($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

			if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
				$this->collPersonas = PersonaPeer::doSelectJoinUsuarioRelatedByUserCreated($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersonaCriteria = $criteria;

		return $this->collPersonas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EstadoCivil is new, it will return
	 * an empty collection; or if this EstadoCivil has previously
	 * been saved, it will retrieve related Personas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EstadoCivil.
	 */
	public function getPersonasJoinUsuarioRelatedByUserUpdated($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$this->collPersonas = PersonaPeer::doSelectJoinUsuarioRelatedByUserUpdated($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

			if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
				$this->collPersonas = PersonaPeer::doSelectJoinUsuarioRelatedByUserUpdated($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersonaCriteria = $criteria;

		return $this->collPersonas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EstadoCivil is new, it will return
	 * an empty collection; or if this EstadoCivil has previously
	 * been saved, it will retrieve related Personas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EstadoCivil.
	 */
	public function getPersonasJoinUsuarioRelatedByUserDeleted($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EstadoCivilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPersonas === null) {
			if ($this->isNew()) {
				$this->collPersonas = array();
			} else {

				$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

				$this->collPersonas = PersonaPeer::doSelectJoinUsuarioRelatedByUserDeleted($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PersonaPeer::ESTADO_CIVIL_ID, $this->id);

			if (!isset($this->lastPersonaCriteria) || !$this->lastPersonaCriteria->equals($criteria)) {
				$this->collPersonas = PersonaPeer::doSelectJoinUsuarioRelatedByUserDeleted($criteria, $con, $join_behavior);
			}
		}
		$this->lastPersonaCriteria = $criteria;

		return $this->collPersonas;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPersonas) {
				foreach ((array) $this->collPersonas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPersonas = null;
			$this->aUsuarioRelatedByUserCreated = null;
			$this->aUsuarioRelatedByUserUpdated = null;
			$this->aUsuarioRelatedByUserDeleted = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseEstadoCivil:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseEstadoCivil::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseEstadoCivil
