<?php


/**
 * Skeleton subclass for performing query and update operations on the 'alumno' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:12 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AlumnoPeer extends BaseAlumnoPeer 
{
  static public function retrieveForAutoSelect($q, $limit)
  {
    $criteria = new Criteria();
    $criteria->addJoin(array(AlumnoPeer::PERSONA_ID,), array(PersonaPeer::ID,));

    $criterion = $criteria->getNewCriterion(PersonaPeer::NOMBRE, '%'.$q.'%', Criteria::LIKE);
    $criterion->addOr($criteria->getNewCriterion(PersonaPeer::APELLIDO, '%'.$q.'%', Criteria::LIKE));

    $criteria->add($criterion);
    $criteria->addAscendingOrderByColumn(PersonaPeer::NOMBRE);
    $criteria->setIgnoreCase(true);
    $criteria->setLimit(10);

    $alumnos = array();

    foreach (AlumnoPeer::doSelect($criteria) as $alumno)
    {
      $alumnos[$alumno->getId()] = (string) $alumno;
    }

    return $alumnos;
	}

} // AlumnoPeer
