<?php


/**
 * Skeleton subclass for representing a row from the 'alumno' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:12 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Alumno extends BaseAlumno {

	/**
	 * Initializes internal state of Alumno object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public function __toString()
	{
		return $this->getPersona()->getNombreCompleto();
	}

	# TODO por el momento no hace nada	
	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AlumnoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
	}

  public function getNombreEstado()
  {
    $estadosPosibles = sfConfig::get('app_estados_Alumno');
    $nombreEstado = array_keys($estadosPosibles, $this->getEstado());

    return(ucwords($nombreEstado[0]));
  }

  static public function getIdByNombreEstado($nombre = null, $desc = false)
  {
    $estadosPosibles = sfConfig::get('app_estados_Alumno');

    if (!is_null($nombre))
    {
      return $estadosPosibles[$nombre];
    }

    if ($desc)
    {
      return $nombreEstado = array_keys($estadosPosibles);
    }

    return $estadosPosibles;
  }

  static public function search($arg = null)
  {
    if (null === $arg || '' === $arg) { return ''; }

    $alumno = AlumnoPeer::retrieveByPK($arg);
    
		return ($alumno && (($nombre = $alumno->getPersona()->getNombreCompleto()) != '')) ? $nombre : '';
  }

} // Alumno
