<?php


/**
 * Skeleton subclass for performing query and update operations on the 'carrera' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:13 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CarreraPeer extends BaseCarreraPeer 
{
  static public function retrieveForAutoSelect($q, $limit)
  {
    $criteria = new Criteria();

    $criteria->add(CarreraPeer::NOMBRE, '%'.$q.'%', Criteria::LIKE);
    $criteria->addAscendingOrderByColumn(CarreraPeer::NOMBRE);
    $criteria->setIgnoreCase(true);
    $criteria->setLimit(10);

    $carreras = array();

    foreach (CarreraPeer::doSelect($criteria) as $carrera)
    {
      $carreras[$carrera->getId()] = (string) $carrera;
    }

		return $carreras;
	}
} // CarreraPeer
