<?php


/**
 * Skeleton subclass for representing a row from the 'carrera' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:13 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Carrera extends BaseCarrera 
{
	public function __toString()
	{
		return $this->getNombre();
	}

  static public function search($arg = null)
  {
    if (null === $arg || '' === $arg) { return ''; }

    $carrera = CarreraPeer::retrieveByPK($arg);
    
		return ($carrera && (($nombre = $carrera->getNombre()) != '')) ? $nombre : '';
  }

  static public function getEstadosBaja()
	{
    return sfConfig::get('app_estados_CarreraBaja');
	}

  public function getNombreEstado()
  {
    $estadosPosibles = sfConfig::get('app_estados_Carrera');
    $nombreEstado = array_keys($estadosPosibles, $this->getEstado());

    return(ucwords($nombreEstado[0]));
  }

  static public function getIdByNombreEstado($nombre = null, $desc = false)
  {
    $estadosPosibles = sfConfig::get('app_estados_Carrera');

    if (!is_null($nombre))
    {
      return $estadosPosibles[$nombre];
    }

    if ($desc)
    {
      return $nombreEstado = array_keys($estadosPosibles);
    }

    return $estadosPosibles;
  }

	public function isDadaBaja()
	{
		return in_array($this->getEstado(), sfConfig::get('app_estados_CarreraBaja'));
	}

	public function darBaja($params, $usuario)
	{
		$this->setEstado($params['carrera']['estado']);
		$this->setObservaciones($this->getObservaciones().'\r\n'.$params['carrera']['observaciones']);
		$this->setDeletedAt(date('Y-m-d H:i:s'));
		$this->setDeletedById($usuario->getId());
		
		$this->save();
	}

} // Carrera
