<?php


/**
 * Skeleton subclass for representing a row from the 'carrera' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:13 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Carrera extends BaseCarrera 
{
	public function __toString()
	{
		return $this->getNombre();
	}

  static public function search($arg = null)
  {
    if (null === $arg || '' === $arg) { return ''; }

    $carrera = CarreraPeer::retrieveByPK($arg);
    
		return ($carrera && (($nombre = $carrera->getNombre()) != '')) ? $nombre : '';
  }

} // Carrera
