<?php


/**
 * Skeleton subclass for performing query and update operations on the 'docente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:15 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DocentePeer extends BaseDocentePeer 
{
  static public function retrieveForAutoSelect($q, $limit)
  {
    $criteria = new Criteria();
    $criteria->addJoin(array(DocentePeer::PERSONA_ID,), array(PersonaPeer::ID,));

    $criterion = $criteria->getNewCriterion(PersonaPeer::NOMBRE, '%'.$q.'%', Criteria::LIKE);
    $criterion->addOr($criteria->getNewCriterion(PersonaPeer::APELLIDO, '%'.$q.'%', Criteria::LIKE));

    $criteria->add($criterion);
    $criteria->addAscendingOrderByColumn(PersonaPeer::NOMBRE);
    $criteria->setIgnoreCase(true);
    $criteria->setLimit(10);

    $docentes = array();

    foreach (DocentePeer::doSelect($criteria) as $docente)
    {
      $docentes[$docente->getId()] = (string) $docente;
    }

    return $docentes;
	}


} // DocentePeer
