<?php


/**
 * Skeleton subclass for representing a row from the 'docente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:15 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Docente extends BaseDocente {

	# TODO por el momento no hace nada	
	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(DocentePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
	}

} // Docente
