<?php


/**
 * Skeleton subclass for representing a row from the 'domicilio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:16 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Domicilio extends BaseDomicilio {
	public function __toString()
	{
      $domicilio = $this->getCalle();
      $domicilio .= ' '.$this->getAltura();
      $domicilio .= ($this->getPiso()) ? ' '.$this->getPiso() : '';
      $domicilio .= ($this->getDpto()) ? ' '.$this->getDpto() : '';
      $domicilio .= ($this->getEscalera()) ? ' Escalera: '.$this->getEscalera() : '';
      $domicilio .= ($this->getTorre()) ? ' Torre: '.$this->getTorre() : '';
      $domicilio .= ($this->getNudo()) ? ' Nudo: '.$this->getNudo() : '';
      $domicilio .= ($this->getAla()) ? ' Ala: '.$this->getAla() : '';
      $domicilio .= ($this->getParcela()) ? ' Parcela: '.$this->getParcela() : '';
      $domicilio .= ($this->getCodigoPostal()) ? ' ('.$this->getCodigoPostal().')' : '';

			return $domicilio;
	}

  public function getDomicilioCompleto()
  {
      $domicilio = $this->getCalle();
      $domicilio .= ' '.$this->getAltura();
      $domicilio .= ($this->getPiso()) ? ' '.$this->getPiso() : '';
      $domicilio .= ($this->getDpto()) ? ' '.$this->getDpto() : '';
      $domicilio .= ($this->getEscalera()) ? ' Escalera: '.$this->getEscalera() : '';
      $domicilio .= ($this->getTorre()) ? ' Torre: '.$this->getTorre() : '';
      $domicilio .= ($this->getNudo()) ? ' Nudo: '.$this->getNudo() : '';
      $domicilio .= ($this->getAla()) ? ' Ala: '.$this->getAla() : '';
      $domicilio .= ($this->getParcela()) ? ' Parcela: '.$this->getParcela() : '';
      $domicilio .= ($this->getCodigoPostal()) ? ' ('.$this->getCodigoPostal().')' : '';
      $domicilio .= ($this->getLocalidadId()) ? ' - '.$this->getLocalidad()->__toString() : '';
      $domicilio .= ($this->getProvinciaId()) ? ' - '.$this->getProvincia()->__toString() : '';

      return $domicilio;
  }
} // Domicilio
