<?php


/**
 * Skeleton subclass for representing a row from the 'tipo_titulo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  6 00:23:20 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TipoTitulo extends BaseTipoTitulo {

} // TipoTitulo
